In [1]:
import requests

In [9]:
URL = 'https://potterapi-fedeperin.vercel.app/en/books'
#uniform Resource Locator
res = requests.get(URL)

In [10]:
json_data = res.json()

In [12]:
import pandas as pd

In [22]:
df = pd.json_normalize(json_data)
df

,number,title,originalTitle,releaseDate,description,pages,cover,index
0,1,Harry Potter and the Sorcerer's Stone,Harry Potter and the Sorcerer's Stone,"Jun 26, 1997","On his birthday, Harry Potter discovers that h...",223,https://raw.githubusercontent.com/fedeperin/po...,0
1,2,Harry Potter and the Chamber of Secrets,Harry Potter and the Chamber of Secrets,"Jul 2, 1998",Harry Potter and the sophomores investigate a ...,251,https://raw.githubusercontent.com/fedeperin/po...,1
2,3,Harry Potter and the Prisoner of Azkaban,Harry Potter and the Prisoner of Azkaban,"Jul 8, 1999",Harry's third year of studies at Hogwarts is t...,317,https://raw.githubusercontent.com/fedeperin/po...,2
3,4,Harry Potter and the Goblet of Fire,Harry Potter and the Goblet of Fire,"Jul 8, 2000",Hogwarts prepares for the Triwizard Tournament...,636,https://raw.githubusercontent.com/fedeperin/po...,3
4,5,Harry Potter and the Order of the Phoenix,Harry Potter and the Order of the Phoenix,"Jun 21, 2003","In his fifth year at Hogwarts, Harry discovers...",766,https://raw.githubusercontent.com/fedeperin/po...,4
5,6,Harry Potter and the Half-Blood Prince,Harry Potter and the Half-Blood Prince,"Jul 16, 2005","Harry discovers a powerful book and, while try...",607,https://raw.githubusercontent.com/fedeperin/po...,5
6,7,Harry Potter and the Deathly Hallows,Harry Potter and the Deathly Hallows,"Jul 21, 2007","Harry, Ron and Hermione go on a dangerous miss...",607,https://raw.githubusercontent.com/fedeperin/po...,6
7,8,Harry Potter and the Cursed Child,Harry Potter and the Cursed Child,"Jul 30, 2016","Harry's second son entered Hogwarts, but in Sl...",336,https://raw.githubusercontent.com/fedeperin/po...,7

In [23]:

df = df[['index', 'originalTitle', 'releaseDate']]
df

   index                              originalTitle   releaseDate
0      0      Harry Potter and the Sorcerer's Stone  Jun 26, 1997
1      1    Harry Potter and the Chamber of Secrets   Jul 2, 1998
2      2   Harry Potter and the Prisoner of Azkaban   Jul 8, 1999
3      3        Harry Potter and the Goblet of Fire   Jul 8, 2000
4      4  Harry Potter and the Order of the Phoenix  Jun 21, 2003
5      5     Harry Potter and the Half-Blood Prince  Jul 16, 2005
6      6       Harry Potter and the Deathly Hallows  Jul 21, 2007
7      7          Harry Potter and the Cursed Child  Jul 30, 2016