In [16]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, recall_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, VotingClassifier

In [4]:
df = pd.read_csv("novagen_dataset.csv")

In [6]:
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9549 entries, 0 to 9548
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    9549 non-null   float64
 1   BMI                    9549 non-null   float64
 2   Blood_Pressure         9549 non-null   float64
 3   Cholesterol            9549 non-null   float64
 4   Glucose_Level          9549 non-null   float64
 5   Heart_Rate             9549 non-null   float64
 6   Sleep_Hours            9549 non-null   float64
 7   Exercise_Hours         9549 non-null   float64
 8   Water_Intake           9549 non-null   float64
 9   Stress_Level           9549 non-null   float64
 10  Target                 9549 non-null   int64
 11  Smoking                9549 non-null   int64
 12  Alcohol                9549 non-null   int64
 13  Diet                   9549 non-null   int64
 14  MentalHealth           9549 non-null   int64
 15  PhysicalActivity       9549 non-null   int64
 16  MedicalHistory         9549 non-null   int64
 17  Allergies              9549 non-null   int64
 18  Diet_Type__Vegan       9549 non-null   bool
 19  Diet_Type__Vegetarian  9549 non-null   bool
 20  Blood_Group_AB         9549 non-null   bool
 21  Blood_Group_B          9549 non-null   bool
 22  Blood_Group_O          9549 non-null   bool
dtypes: bool(5), float64(10), int64(8)
memory usage: 1.4 MB

In [8]:
df.isnull().sum()

Age                      0
BMI                      0
Blood_Pressure           0
Cholesterol              0
Glucose_Level            0
Heart_Rate               0
Sleep_Hours              0
Exercise_Hours           0
Water_Intake             0
Stress_Level             0
Target                   0
Smoking                  0
Alcohol                  0
Diet                     0
MentalHealth             0
PhysicalActivity         0
MedicalHistory           0
Allergies                0
Diet_Type__Vegan         0
Diet_Type__Vegetarian    0
Blood_Group_AB           0
Blood_Group_B            0
Blood_Group_O            0
dtype: int64

In [10]:
df["Target"].head()

0    1
1    1
2    0
3    0
4    0
Name: Target, dtype: int64

In [11]:
# conert bool to numbers
df[['Diet_Type__Vegan', 'Diet_Type__Vegetarian', 'Blood_Group_AB', 'Blood_Group_B', 'Blood_Group_O']] = df[['Diet_Type__Vegan', 'Diet_Type__Vegetarian', 'Blood_Group_AB', 'Blood_Group_B', 'Blood_Group_O']].astype('int64')

In [12]:
df.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,0,1,1,0,0
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,0,0,1,0,0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,1,0,0,0,0
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,1,0,0,1,0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,0,1,0,1,0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9549 entries, 0 to 9548
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    9549 non-null   float64
 1   BMI                    9549 non-null   float64
 2   Blood_Pressure         9549 non-null   float64
 3   Cholesterol            9549 non-null   float64
 4   Glucose_Level          9549 non-null   float64
 5   Heart_Rate             9549 non-null   float64
 6   Sleep_Hours            9549 non-null   float64
 7   Exercise_Hours         9549 non-null   float64
 8   Water_Intake           9549 non-null   float64
 9   Stress_Level           9549 non-null   float64
 10  Target                 9549 non-null   int64
 11  Smoking                9549 non-null   int64
 12  Alcohol                9549 non-null   int64
 13  Diet                   9549 non-null   int64
 14  MentalHealth           9549 non-null   int64
 15  PhysicalActivity       9549 non-null   int64
 16  MedicalHistory         9549 non-null   int64
 17  Allergies              9549 non-null   int64
 18  Diet_Type__Vegan       9549 non-null   int64
 19  Diet_Type__Vegetarian  9549 non-null   int64
 20  Blood_Group_AB         9549 non-null   int64
 21  Blood_Group_B          9549 non-null   int64
 22  Blood_Group_O          9549 non-null   int64
dtypes: float64(10), int64(13)
memory usage: 1.7 MB

In [17]:
X = df.drop("Target", axis=1)
y = df["Target"]

In [18]:
X.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,0,1,1,0,0
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,0,0,1,0,0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,1,0,0,0,0
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,1,0,0,1,0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,0,1,0,1,0

In [19]:
y.head()

0    1
1    1
2    0
3    0
4    0
Name: Target, dtype: int64

In [28]:
# scaling
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Model 1 (LogReg)

In [29]:
lr = LogisticRegression(
    penalty="l2",
    solver="liblinear",
    max_iter=1000
)
lr.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [53]:
y_pred = lr.predict(X_test_scaled)

print(f"LogReg Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print(f"LogReg Recall: {recall_score(y_test, y_pred) * 100:.2f}%")

LogReg Accuracy: 81.41%
LogReg Recall: 82.83%

# Model 2 (kNN)

In [33]:
knn = KNeighborsClassifier(
    n_neighbors=5,
    metric="euclidean"
)

knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(metric='euclidean')

In [52]:
y_pred = knn.predict(X_test_scaled)

print(f"kNN Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print(f"kNN Recall: {recall_score(y_test, y_pred) * 100:.2f}%")

kNN Accuracy: 88.32%
kNN Recall: 88.35%

# Random Forest Classifier

In [36]:
rfc = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42
)

rfc.fit(X_train_scaled, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [51]:
y_pred = rfc.predict(X_test_scaled)

print(f"RFC Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print(f"RFC Recall: {recall_score(y_test, y_pred) * 100:.2f}%")

RFC Accuracy: 93.98%
RFC Recall: 96.18%

# Gradient Boosting Classifer

In [40]:
gbc = GradientBoostingClassifier(
    n_estimators=150,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gbc.fit(X_train_scaled, y_train)

GradientBoostingClassifier(n_estimators=150, random_state=42)

In [50]:
y_pred = gbc.predict(X_test_scaled)

print(f"GBC Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print(f"GBC Recall: {recall_score(y_test, y_pred) * 100:.2f}%")

GBC Accuracy: 93.04%
GBC Recall: 94.98%

# Voting Classifier

In [60]:
vc = VotingClassifier(
    estimators=[
        ("lr",lr),
        ("knn",knn),
        ("rf",rfc)],
    voting="soft"
)

vc.fit(X_train_scaled, y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(max_iter=1000,
                                                 solver='liblinear')),
                             ('knn', KNeighborsClassifier(metric='euclidean')),
                             ('rf',
                              RandomForestClassifier(n_estimators=200,
                                                     random_state=42))],
                 voting='soft')

In [49]:
y_pred = vc.predict(X_test_scaled)

print(f"VC Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print(f"VC Recall: {recall_score(y_test, y_pred) * 100:.2f}%")

VC Accuracy: 91.57%
VC Recall: 92.97%

In [58]:

data = {
    "Model": ["LogisticReggression", "kNN", "Random Forest Classifier", "Gradient Boosting Classifier", "Voting Classifier"],
    "Accuracy (%)": [81.41, 88.32, 93.98, 93.04, 91.57],
    "Recall (%)": [82.83, 88.35, 96.18, 94.98, 92.97]
}
df = pd.DataFrame(data)
df

                          Model  Accuracy (%)  Recall (%)
0           LogisticReggression         81.41       82.83
1                           kNN         88.32       88.35
2      Random Forest Classifier         93.98       96.18
3  Gradient Boosting Classifier         93.04       94.98
4             Voting Classifier         91.57       92.97

# from the above we can judge that "Random Forest Classifier" model is best for the NovaGen Research Labs with accuracy : 93.98%