In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Avinash","Akhbar","Amar","Antony"],
    "CGPA" : [99.9,97.5,98.5,87.7]
}
df = pd.DataFrame(info) # it will make the dict as table (strctured way)

print(df)

      Name  CGPA
0  Avinash  99.9
1   Akhbar  97.5
2     Amar  98.5
3   Antony  87.7

In [4]:
df #dataframe

      Name  CGPA
0  Avinash  99.9
1   Akhbar  97.5
2     Amar  98.5
3   Antony  87.7

In [8]:
# Series
s = pd.Series([1,2,3,4,5])
print(s)
type(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

pandas.core.series.Series

In [11]:
#index (index based access)
print(s[2])
print(s[0])

3
1

In [15]:
# labelled based access
s = pd.Series([1,2,3,4], index=["Avinash","Charlie","Sheldon","Lenord"])
print(s)
print('\n')
print(s["Sheldon"])

Avinash    1
Charlie    2
Sheldon    3
Lenord     4
dtype: int64


3

In [16]:
# Properties
# 1. Homogenous
s = pd.Series([1,2,3,4,"abc"], index=["Avinash","Charlie","Sheldon","Lenord",123])
print(s)

Avinash      1
Charlie      2
Sheldon      3
Lenord       4
123        abc
dtype: object

In [18]:
# 2. Vectorized Operations
s1 = pd.Series([1,2,3,4,5,6,7])
s2 = pd.Series([5,6,7,8,9,10,11])
print(s1 + s2)

0     6
1     8
2    10
3    12
4    14
5    16
6    18
dtype: int64

In [19]:
# Handle Mising Value with NaN
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([5,6,7,8,9,10,11])
print(s1 + s2)

0     6.0
1     8.0
2    10.0
3    12.0
4     NaN
5     NaN
6     NaN
dtype: float64

In [22]:
# Mutable values, immutable size
s1 = pd.Series([1,2,3,4])
print(s1) # origial series
s1[0] = 100
changed_s = s1.drop(0)
print(s1) # after 
print(changed_s) # changed series droping 1 index

0    1
1    2
2    3
3    4
dtype: int64
0    100
1      2
2      3
3      4
dtype: int64
1    2
2    3
3    4
dtype: int64

In [27]:
# Data Frame
info = { # dict of lists
    "Name": ["Avinash","Bob","Charlie","Sheldon"],
    "Age":[24,54,12,45],
    "CGPA":[98,34,56,1]
}

df = pd.DataFrame(info)
print(df, type(df))

print(df.index)
print(df.columns)

      Name  Age  CGPA
0  Avinash   24    98
1      Bob   54    34
2  Charlie   12    56
3  Sheldon   45     1 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [32]:
# lists of lists

df = pd.DataFrame([["Avinash",1],["Adam",2],["Akhbar",4]], columns=["Name","Roll NO"])
print(df)

      Name  Roll NO
0  Avinash        1
1     Adam        2
2   Akhbar        4

In [33]:
df

      Name  Roll NO
0  Avinash        1
1     Adam        2
2   Akhbar        4

In [34]:
import numpy as np

In [38]:
 # np array way
np_arry = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arry, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [39]:
df

   A  B  C
0  1  2  3
1  4  5  6

In [40]:
# csv data
df = pd.read_csv("employee_data.csv")
print(df, type(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [42]:
# read json
df = pd.read_json("panda.json")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [43]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [44]:
# Methods
print(df.head()) # starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [47]:
print(df.tail(2)) # last 2 rows

   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [51]:
print(df.sample()) # random row displyed
print('\n')
print(df.sample(4))

   ID    Name  Age Department  Salary
7   8  Hannah   26  Marketing   47000


   ID    Name  Age Department  Salary
7   8  Hannah   26  Marketing   47000
3   4   David   45  Marketing   91000
0   1   Alice   25         HR   55000
9  10   Julia   30    Finance   60000

In [52]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None

In [53]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [54]:
print(df.shape) # number of row and coloums value

(10, 5)

In [57]:
print(df.describe())

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [59]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [60]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [61]:
print(df.nunique())

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [64]:
# AQI dataset

df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [65]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [66]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [67]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [72]:
# selecting data
 #1. select columns
df["country"]
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [83]:
 # 2. select rows (labael & index based)- loc & iloc
# Label - loc
# Index - iloc

print(df.loc[0:2]) # start idx: end idx (inclusive)   - label
print(df.loc[0])

                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783

   wind_speed
0       3.725
1       8.969
2       9.650
timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [81]:
df.iloc[0:2]  # start idx: end idx (exclusice)   - index based

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [82]:
df.iloc[0]

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [88]:
# cell -row, col
df.loc[0:2, ["city","aqi"]]

       city  aqi
0  New York  108
1  New York   90
2  New York   84

In [86]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [91]:
df.iloc[0:2, 1:5] #( range(:) row , range(:) columns) all in numbers

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006

In [94]:
df.loc[0:1, ["city","aqi","country","longitude"]] #( range(:) row , range(:) columns) numbers and strings (objects)

       city  aqi country  longitude
0  New York  108      US    -74.006
1  New York   90      US    -74.006

In [101]:
df.loc[0:"city"]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [100]:
df.iloc[0,2]

'New York'

In [103]:
df.at[0,"city"]

'New York'

In [99]:
df.iat[0,2]

'New York'

In [121]:
# filtering data

df[df["aqi"] > 100] # single condition
df[(df["aqi"] > 100) & (df["temperature"] > 30)]  
# for above multiple condition { & = ampercent = and operator; | = pipe operator = or; ~ = tilt operator = not}
df[(df["aqi"] > 100) & (df["temperature"] < 30)] 

#chaining
aqi_data = df[(df["aqi"] > 100) & (df["temperature"] > 30)] [["city","aqi"]]

aqi_data.iloc[0] # 1st value in df
#aqi_data.loc[0] - this will get error
aqi_data.loc[6] # this is correct way

city    New York
aqi          155
Name: 6, dtype: object

## Query Method (Important)

In [124]:
# Query Method
aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [130]:
# Cleaning Data
# 1. Missing values
#a. isnull() / isna()

df = pd.read_csv("raw_data.csv")

df.isnull() # shows all the NaN (not a number values/ missing value) as "True"
df.isna() # alias for df.isnull()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [133]:
df.isnull().sum() # count for missing values

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [134]:
df.dropna() # it will drop the row which contain atleast 1 NaN/Missing value/Empty space and shows the new df

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [136]:
df.dropna(axis=1) # drop col

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [140]:
df.fillna("(Missing Value)") # replace/fill the empty space

,id,name,age,country,gender,income
0,1,John Doe,29.0,USA,Male,55000.0
1,1,John Doe,29.0,USA,Male,55000.0
2,2,Jane Smith,(Missing Value),Canada,Female,62000.0
3,3,Alex,(Missing Value),USA,Unknown,47000.0
4,4,Maria Garcia,34.0,Spain,Female,(Missing Value)
5,5,Li Wei,27.0,China,Male,51000.0
6,6,(Missing Value),45.0,India,Female,73000.0
7,7,Ahmed Khan,38.0,(Missing Value),Male,68000.0
8,8,Rachel Lee,29.0,USA,Female,62000.0
9,9,Carlos Ruiz,(Missing Value),Mexico,Male,45000.0
10,10,Emily Davis,31.0,USA,(Missing Value),58000.0

In [151]:
# to replace avg values of age on missing values
age_mean = df["age"].mean() # this will get the mean value of age

cleaned_data = df.copy() # this will make the copy/dulplicate dataframe
age_mean = cleaned_data["age"].mean() # this will get the mean value of age of copy df
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean) # this will store the filled mean age in the age_col of copy df named "cleaned_data
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [153]:
df.ffill() # filling the value which is above the missing space into the missing space

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [154]:
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [156]:
#2. Handle Duplicate Values

df.duplicated() # it will find thhe duplicate row

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [158]:
df["country"].duplicated() # see for specific col duplicates

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
Name: country, dtype: bool

In [159]:
df[["country","gender"]].duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [162]:
df.drop_duplicates() # i will remove the duplicates row

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [273]:
df2 = df.copy() # make a copy of df to df2
df2.drop_duplicates(inplace=True) # DROP THE dupliactes and amke chages in original df

In [274]:
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [275]:
# Data Types

df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [276]:
# to change 'age' data type float to int
df2 = df.copy()
df2 = df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy() 
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [277]:
 df2 # converted to int

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [278]:
# data time dtype
date_time = pd.Series([pd.to_datetime("2001-09-23")])
type(date_time.dtypes)

numpy.dtypes.DateTime64DType

In [279]:
aqi_data = pd.read_csv("globalAirQuality.csv") # to read the csv file
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"]) # to change it to date time dtype
type(aqi_data["timestamp"].dtypes)

numpy.dtypes.DateTime64DType

In [280]:
# Handle Strings

df["gender"].str.lower() # all lower letters of the word/string

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [281]:
df["gender"].str.upper() # all capital letter of word

0        MALE
1        MALE
2      FEMALE
3     UNKNOWN
4      FEMALE
5        MALE
6      FEMALE
7        MALE
8      FEMALE
9        MALE
10        NaN
Name: gender, dtype: object

In [282]:
df["gender"].str.capitalize() # starting letter only capital

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [283]:
df["country"].str.strip() # to remove the extra spaces

0        USA
1        USA
2     Canada
3        USA
4      Spain
5      China
6      India
7        NaN
8        USA
9     Mexico
10       USA
Name: country, dtype: object

In [284]:
df["country"].str.split("") # split the letters or words

0              [, U, S, A, ]
1              [, U, S, A, ]
2     [, C, a, n, a, d, a, ]
3              [, U, S, A, ]
4        [, S, p, a, i, n, ]
5        [, C, h, i, n, a, ]
6        [, I, n, d, i, a, ]
7                        NaN
8              [, U, S, A, ]
9     [, M, e, x, i, c, o, ]
10             [, U, S, A, ]
Name: country, dtype: object

In [285]:
df["name"].str.split(" ") # spliting the senetence with space

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [286]:
df["name"].str.split(" ")[1][1] # split the words/ letters from 'which' value with chained selection

'Doe'

In [287]:
df["country"].str.contains("USA") # TO FIND THE  values given

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

In [288]:
df["country"].str.contains("india", case=False) # it will find the the value and then disable the case sensitive to find easily

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [289]:
# Transformation Data (Feature engineering)

df2 = df.copy()
df2["tax"] = df2["income"].apply(lambda x : "20%" if x >=60000 else "10%") # here a lambda function passed (High order function)
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

In [290]:
# to change male as M, female  as F, Unknown as U

gender_map = {"Male":"M","Female":"F","Unknown":"U"}
df2["gender"] = df2["gender"].map(gender_map) # map the values
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [291]:
df2.assign(new_income = df2["income"] * 1.1) # it will assign the new vlaus to new columns from existing data

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

In [292]:
df2["country"] = df2["country"].replace("US","United States")
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [293]:
# Rename coloumns old to new
df2.columns = ["Id","Name","Age","Country","Gender","Income","Tax"]
df2

    Id          Name   Age Country Gender   Income  Tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [294]:
df2.rename(columns={"Income":"Salary"})

    Id          Name   Age Country Gender   Salary  Tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [295]:
df2.rename(index={1:"First"}) # to change the row/index name to rename

       Id          Name   Age Country Gender   Income  Tax
0       1      John Doe  29.0     USA      M  55000.0  10%
First   1      John Doe  29.0     USA      M  55000.0  10%
2       2    Jane Smith   NaN  Canada      F  62000.0  20%
3       3          Alex   NaN     USA      U  47000.0  10%
4       4  Maria Garcia  34.0   Spain      F      NaN  10%
5       5        Li Wei  27.0   China      M  51000.0  10%
6       6           NaN  45.0   India      F  73000.0  20%
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8       8    Rachel Lee  29.0     USA      F  62000.0  20%
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10     10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [300]:
df2.sort_values("Age") # asending order of age and index are jumbled

    Id          Name   Age Country Gender   Income  Tax
5    5        Li Wei  27.0   China      M  51000.0  10%
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%

In [301]:
df2.sort_values(["Income","Age"]) # if 2 incomes are equal than based on 'Age' sorted

    Id          Name   Age Country Gender   Income  Tax
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
3    3          Alex   NaN     USA      U  47000.0  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%

In [320]:
sorted_df = df2.sort_values("Age",ascending=False) # in opp order/ dsecending order
sorted_df

    Id          Name   Age Country Gender   Income  Tax
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
5    5        Li Wei  27.0   China      M  51000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%

In [321]:
sorted_df.sort_index() # it will resort to original .i.e in the sorted index format

    Id          Name   Age Country Gender   Income  Tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [322]:
sorted_df.reset_index() 
#wanted sorted df but the index values has to be from 
#jubbled to asending order from (0 to infinity)

    index  Id          Name   Age Country Gender   Income  Tax
0       6   6           NaN  45.0   India      F  73000.0  20%
1       7   7    Ahmed Khan  38.0     NaN      M  68000.0  20%
2       4   4  Maria Garcia  34.0   Spain      F      NaN  10%
3      10  10   Emily Davis  31.0     USA    NaN  58000.0  10%
4       0   1      John Doe  29.0     USA      M  55000.0  10%
5       1   1      John Doe  29.0     USA      M  55000.0  10%
6       8   8    Rachel Lee  29.0     USA      F  62000.0  20%
7       5   5        Li Wei  27.0   China      M  51000.0  10%
8       2   2    Jane Smith   NaN  Canada      F  62000.0  20%
9       3   3          Alex   NaN     USA      U  47000.0  10%
10      9   9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%

In [323]:
sorted_df.reset_index(drop=True) #we can drop the previous sorted df to previous one

    Id          Name   Age Country Gender   Income  Tax
0    6           NaN  45.0   India      F  73000.0  20%
1    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
2    4  Maria Garcia  34.0   Spain      F      NaN  10%
3   10   Emily Davis  31.0     USA    NaN  58000.0  10%
4    1      John Doe  29.0     USA      M  55000.0  10%
5    1      John Doe  29.0     USA      M  55000.0  10%
6    8    Rachel Lee  29.0     USA      F  62000.0  20%
7    5        Li Wei  27.0   China      M  51000.0  10%
8    2    Jane Smith   NaN  Canada      F  62000.0  20%
9    3          Alex   NaN     USA      U  47000.0  10%
10   9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%

In [324]:
df2.rank() # it will assign rank to all value of columns

      Id  Name  Age  Country  Gender  Income  Tax
0    1.5   6.5  3.0      8.0     7.0     4.5  4.0
1    1.5   6.5  3.0      8.0     7.0     4.5  4.0
2    3.0   5.0  NaN      1.0     2.5     7.5  9.5
3    4.0   2.0  NaN      8.0    10.0     2.0  4.0
4    5.0   9.0  6.0      5.0     2.5     NaN  4.0
5    6.0   8.0  1.0      2.0     7.0     3.0  4.0
6    7.0   NaN  8.0      3.0     2.5    10.0  9.5
7    8.0   1.0  7.0      NaN     7.0     9.0  9.5
8    9.0  10.0  3.0      8.0     2.5     7.5  9.5
9   10.0   3.0  NaN      4.0     7.0     1.0  4.0
10  11.0   4.0  5.0      8.0     NaN     6.0  4.0

In [327]:
sorted_df = df2.sort_values("Age",ascending=True) # in opp order/ dsecending order
sorted_df

    Id          Name   Age Country Gender   Income  Tax
5    5        Li Wei  27.0   China      M  51000.0  10%
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
6    6           NaN  45.0   India      F  73000.0  20%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%

In [334]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False) # if we want rank of 
# a perticuler coloumn in ascending/opps.

In [335]:
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
5    5        Li Wei  27.0   China      M  51000.0  10%      8.0
0    1      John Doe  29.0     USA      M  55000.0  10%      6.5
1    1      John Doe  29.0     USA      M  55000.0  10%      6.5
8    8    Rachel Lee  29.0     USA      F  62000.0  20%      3.5
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%      5.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%      NaN
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%      2.0
6    6           NaN  45.0   India      F  73000.0  20%      1.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%      3.5
3    3          Alex   NaN     USA      U  47000.0  10%      9.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     10.0

In [338]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="dense")
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
5    5        Li Wei  27.0   China      M  51000.0  10%      6.0
0    1      John Doe  29.0     USA      M  55000.0  10%      5.0
1    1      John Doe  29.0     USA      M  55000.0  10%      5.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%      3.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%      4.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%      NaN
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%      2.0
6    6           NaN  45.0   India      F  73000.0  20%      1.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%      3.0
3    3          Alex   NaN     USA      U  47000.0  10%      7.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%      8.0

In [339]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="min") 
# solve the tie for lower value
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
5    5        Li Wei  27.0   China      M  51000.0  10%      8.0
0    1      John Doe  29.0     USA      M  55000.0  10%      6.0
1    1      John Doe  29.0     USA      M  55000.0  10%      6.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%      3.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%      5.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%      NaN
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%      2.0
6    6           NaN  45.0   India      F  73000.0  20%      1.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%      3.0
3    3          Alex   NaN     USA      U  47000.0  10%      9.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     10.0

In [340]:
sorted_df["Ranking"] = sorted_df["Income"].rank(ascending=False, method="max") 
# solve the tie for higher value
sorted_df

    Id          Name   Age Country Gender   Income  Tax  Ranking
5    5        Li Wei  27.0   China      M  51000.0  10%      8.0
0    1      John Doe  29.0     USA      M  55000.0  10%      7.0
1    1      John Doe  29.0     USA      M  55000.0  10%      7.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%      4.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%      5.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%      NaN
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%      2.0
6    6           NaN  45.0   India      F  73000.0  20%      1.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%      4.0
3    3          Alex   NaN     USA      U  47000.0  10%      9.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     10.0

In [397]:
sorted_df[["Name","Id","Country","Age","Income","Gender","Tax","Ranking","Income"]] 

# just reassigne/reorder the position of the columns by manual

            Name  Id Country   Age   Income Gender  Tax  Ranking   Income
5         Li Wei   5   China  27.0  51000.0      M  10%      8.0  51000.0
0       John Doe   1     USA  29.0  55000.0      M  10%      7.0  55000.0
1       John Doe   1     USA  29.0  55000.0      M  10%      7.0  55000.0
8     Rachel Lee   8     USA  29.0  62000.0      F  20%      4.0  62000.0
10   Emily Davis  10     USA  31.0  58000.0    NaN  10%      5.0  58000.0
4   Maria Garcia   4   Spain  34.0      NaN      F  10%      NaN      NaN
7     Ahmed Khan   7     NaN  38.0  68000.0      M  20%      2.0  68000.0
6            NaN   6   India  45.0  73000.0      F  20%      1.0  73000.0
2     Jane Smith   2  Canada   NaN  62000.0      F  20%      4.0  62000.0
3           Alex   3     USA   NaN  47000.0      U  10%      9.0  47000.0
9    Carlos Ruiz   9  Mexico   NaN  45000.0      M  10%     10.0  45000.0

In [404]:
 # practice task
# shift 'id' col to end

list1 = []
col = 'Id'
for i,x in enumerate(sorted_df.columns):
    if (i == (len(sorted_df.columns))-1):
        list1.append(col)
    elif x != col:
        list1.append(x)
sorted_df[list1]

            Name   Age Country Gender   Income  Tax  Id
5         Li Wei  27.0   China      M  51000.0  10%   5
0       John Doe  29.0     USA      M  55000.0  10%   1
1       John Doe  29.0     USA      M  55000.0  10%   1
8     Rachel Lee  29.0     USA      F  62000.0  20%   8
10   Emily Davis  31.0     USA    NaN  58000.0  10%  10
4   Maria Garcia  34.0   Spain      F      NaN  10%   4
7     Ahmed Khan  38.0     NaN      M  68000.0  20%   7
6            NaN  45.0   India      F  73000.0  20%   6
2     Jane Smith   NaN  Canada      F  62000.0  20%   2
3           Alex   NaN     USA      U  47000.0  10%   3
9    Carlos Ruiz   NaN  Mexico      M  45000.0  10%   9

In [411]:
new_col_order = [col for col in sorted_df.columns if col != 'Id'] + ['Id'] # more and more better than above

sorted_df[new_col_order]

            Name   Age Country Gender   Income  Tax  Ranking  Id
5         Li Wei  27.0   China      M  51000.0  10%      8.0   5
0       John Doe  29.0     USA      M  55000.0  10%      7.0   1
1       John Doe  29.0     USA      M  55000.0  10%      7.0   1
8     Rachel Lee  29.0     USA      F  62000.0  20%      4.0   8
10   Emily Davis  31.0     USA    NaN  58000.0  10%      5.0  10
4   Maria Garcia  34.0   Spain      F      NaN  10%      NaN   4
7     Ahmed Khan  38.0     NaN      M  68000.0  20%      2.0   7
6            NaN  45.0   India      F  73000.0  20%      1.0   6
2     Jane Smith   NaN  Canada      F  62000.0  20%      4.0   2
3           Alex   NaN     USA      U  47000.0  10%      9.0   3
9    Carlos Ruiz   NaN  Mexico      M  45000.0  10%     10.0   9